### ISSUE TITLE
Create Database

### ISSUE THREAD

**Issue by ashleysullins** [ashleysullins/gems#2]
Database name: gem
Database test name: gem_test

![image](https://cloud.githubusercontent.com/assets/5841571/9770478/3ff319d6-56e5-11e5-9a31-b766ec38a881.png)

- [ ] Save as .sql
- [ ] Gem names can be found here: http://steven-universe.wikia.com/wiki/Fusion_Gems

**Comment by seg2136** [comment]
Database Join Statement Example:
gem=# SELECT gems.* FROM fusions
gem-# JOIN combos ON (fusions.id = combos.fusion_id)
gem-# JOIN gems ON (combos.gem1_id = gems.id)
gem-# WHERE fusions.id = 1;

id | gem_name | potential_pairs 
----+----------+-----------------
  2 | Amethyst | {3,1}
  3 | Pearl    | {2,4,1}
(2 rows)

**Comment by seg2136** [comment]
Gems:
Garnet = 1
Amethyst = 2
Pearl = 3
Rose Quartz = 4
Jasper = 5
Lapis Lazuli = 6

Fusions:
Opal = 1
Sugilite = 2
Malachite = 3
Rainbow Quartz = 4
Sardonyx = 5

gem=# SELECT * FROM gems;
 id |   gem_name   | potential_pairs 
----+--------------+-----------------
  1 | Garnet       | {2,3}
  2 | Amethyst   | {3,1}
  3 | Pearl         | {2,4,1}
  4 | Rose Quartz  | {3}
  5 | Jasper       | {6}
  6 | Lapis Lazuli | {5}
(6 rows)

gem=# SELECT * FROM fusions;
 id |  fusion_name   |                      description                       
----+----------------+--------------------------------------------------------
  1 | Opal            | Ultra-powerful, stone-cold Betty.
  2 | Sugilite        | Nicki Minaj.
  3 | Malachite      | Maniacal and a little insane.
  4 | Rainbow Quartz | Sassy 80s dancer and singer.
  5 | Sardonyx       | Careful, elegant, powerful, intelligent, and accurate.
(5 rows)

gem=# SELECT * FROM combos;
 id | gem1_id | gem2_id | fusion_id 
----+---------+---------+-----------
  1 |       1 |       2 |         2
  2 |       1 |       3 |         5
  3 |       2 |       3 |         1
  4 |       2 |       1 |         2
  5 |       3 |       2 |         1
  6 |       3 |       4 |         4
  7 |       3 |       1 |         5
  8 |       4 |       3 |         4
  9 |       5 |       6 |         5
 10 |       6 |       5 |         5
(10 rows)
